---
 local: true
 web_prefix: /home/natuyuki/ml_webapp/
 local_cache_filepath: 'F:\python_stuff\hdb_project_cache'
 use_datetime: true
 year: 
   - 2023
 months: #if using for determining which model to use, it takes the last item
   - 1
   - 2
   - 3
   - 4
   - 5
 train: 'static/train.csv'
 test: 'static/test.csv'
 model_version: '2023_9'