---
 local: False # Whether to run app.py locally or on pythonanywhere
 web_prefix: /home/natuyuki/ml_webapp/
 local_cache_filepath: 'ignore/hdb_project_cache'
 use_datetime: true # For extracting from data.gov.sg (using latest data)
 year: # For extracting from data.gov.sg
   - 2023
 months: # For extracting from data.gov.sg
   - 1
   - 2
   - 3
   - 4
   - 5
 train: 'static/train.csv'
 test: 'static/test.csv'
 model_version: '2023_11'
 save_model_version: '2023_11' # For saving built model
 automation: True # For recurrent runs at the end of each month